[package]
name = "lembeh"
version = "0.1.0"
authors = ["el'diablo <eldiablolives@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.9.0"

[[bin]]
name = "lembeh"
path = "main.rs"
